LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS     := optional
LOCAL_MODULE          := Music
LOCAL_SRC_FILES       := M.apk
LOCAL_CERTIFICATE     := PRESIGNED
LOCAL_MODULE_CLASS    := APPS
LOCAL_MODULE_SUFFIX   := .apk
LOCAL_DEX_PREOPT      := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS     := optional
LOCAL_MODULE          := Gallery
LOCAL_SRC_FILES       := G.apk
LOCAL_CERTIFICATE     := PRESIGNED
LOCAL_MODULE_CLASS    := APPS
LOCAL_MODULE_SUFFIX   := .apk
LOCAL_DEX_PREOPT      := false
include $(BUILD_PREBUILT)
